### ISSUE TITLE
Alternative payment

### ISSUE THREAD

**Issue by reignmacker** [djade007/flutter_paystack_client#1]
@djade007 I want to make payment with other options like mobile money enabled. How should i go around it. Thank you

**Comment by djade007** [comment]
Is this for web or mobile app?

**Comment by reignmacker** [comment]
> Is this for web or mobile app?

mobile app

**Comment by djade007** [comment]
Have you tried this plugin: https://pub.dev/packages/flutter_paystack?

**Comment by reignmacker** [comment]
Mobile app


Sent from Yahoo Mail for iPhone


On Wednesday, April 21, 2021, 1:43 PM, Afeez Olajide ***@***.***> wrote:




Is this for web or mobile app?

**Comment by reignmacker** [comment]
> https://pub.dev/packages/flutter_paystack

Well i have to migrate to null safety first and i have well over 20 packages which is not on null safety it will cause a lot of errors in the app which is not an ideal solution.
i tried https://pub.dev/packages/paystack_manager but the problem is routing back to homepage after successful transaction.

**Comment by djade007** [comment]
You will need to use an old version of plugin.
You can include the **exact** version in your pubspec

Don't use this ❌
`flutter_paystack: ^1.0.4+1` 

Use this instead ✅
`flutter_paystack: 1.0.4+1`
