### ISSUE TITLE
South African merchant web transaction fails

### ISSUE THREAD

**Issue by disparta** [djade007/flutter_paystack_client#2]
Hello, when im trying to start a transaction using web i keep getting an error: "We could not start this transaction. Currency not supported by the merchant." 

<img width="1440" alt="Screenshot 2021-05-17 at 08 10 43" src="https://user-images.githubusercontent.com/17022203/118440207-99dc8a00-b6e7-11eb-8819-f6fdd4c40495.png">

It works fine on iOS, do you perchance know how I can fix this?

Thanks.

**Comment by djade007** [comment]
I think you may have to reach out to Paystack support for this issue. But before that, can you try a simple HTML and JavaScript payment test to be sure it's an issue from Paystack.

You can copy the HTML and JS code from https://paystack.com/docs/payments/accept-payments

**Comment by GoodwillEddicus** [comment]
@disparta were you able to find a workaround for the ZAR currency or get support from the team?

**Comment by disparta** [comment]
@GoodwillEddicus, yeah. I changed some parts of the code and it started working. It looks like it defaulted to NGN and SA merchants can't process that yet. If you're still in the 2019 MTN ICT Challenge WhatsApp group I can send you the code.

**Comment by GoodwillEddicus** [comment]
@disparta Great suggestion - I just noticed looking into the package that the currency is defaulting to a constant (Nigerian currency) - I'll play around with the variables for a solution - but no harm in using your solution if you have it handy.

I'm not in the group anymore, or on WhatsApp, but you can reach out via email: goodwill@eddicus.dev - and we can connect from there via Signal.

Thanks in advance - look forward to chatting further.

**Comment by GoodwillEddicus** [comment]
In case anybody else struggles with the same thing - the problem is that even if you specify the currency and locale values on the Charge object, they're not being passed to the popup, the 'schema' or class is not set to accept those two.

The fix: Update paystack_js.dart to accept locale and currency and then define those in your Charge object when initiating payment.
