### ISSUE TITLE
mobile payment option

### ISSUE THREAD

**Issue by childon4god** [djade007/flutter_paystack_client#3]
in the web App I got different option of payment like   Card, Bank, USSD, QR.
But in the Mobile App I got one i.e Card option

**Comment by djade007** [comment]
This package uses the official [Paystack PopJs](https://paystack.com/docs/payments/accept-payments/#popup) for Web and [flutter_paystack](https://pub.dev/packages/flutter_paystack) plugin for mobile. You can review the documentation or request for a new feature at https://github.com/wilburt/flutter_paystack
