### ISSUE TITLE
Bank transfer options and others

### ISSUE THREAD

**Issue by childon4god** [djade007/flutter_paystack_client#4]
Can you implement some other options in the web. 
Like bank tranfer, ussd etc in the andriod and ios

**Comment by djade007** [comment]
Hello @childon4god this package provides a web implementation but wraps https://github.com/wilburt/flutter_paystack for the mobile implementation. You may want to [open an issue](https://github.com/wilburt/flutter_paystack/issues) there for the mobile support.

**Comment by Princewil** [comment]
I think this package gives other options as the web https://pub.dev/packages/flutter_paystack_plus
